version: "3"

services:
  openldap:
    image: osixia/openldap:latest
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - 8000:80
      - 6443:443
