openapi: 3.0.2
info:
  title: LDAPjs 测试
  version: 0.0.1
servers:
  - url: http://localhost:3000
paths:
  /login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            example:
              username: xiawei
              password: "123"
            schema:
              $ref: "#/components/schemas/LoginDto"
        required: true
      responses:
        "200":
          content:
            application/json:
              example: Success
              schema:
                type: string
          description: OK
      summary: 用户登录
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    LoginDto:
      example:
        password: password
        username: username
      properties:
        username:
          type: string
        password:
          type: string
      type: object
