openapi: 3.0.2

info:
  version: 0.0.1
  title: LDAPjs 测试

servers:
  - url: http://localhost:3000

paths:
  /login:
    post:
      summary: 用户登录
      operationId: login

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
            example:
              username: xiawei
              password: "123"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
              example: "Success"

components:
  schemas:
    LoginDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
