openapi: 3.0.2

info:
  version: 0.0.1
  title: LDAPjs 测试

servers:
  - url: http://localhost:3000

paths:
  /login:
    post:
      summary: 用户登录
      operationId: login

      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
