#!/bin/bash
API_FILE="ums-openapi.yaml"
OUTPUT_DIR="$(dirname $PWD)/server"

buildServer() {
    
    docker run --rm -u $(id -u):$(id -g) \
     -v $OUTPUT_DIR:/output \
     -v $PWD:/input \
    openapitools/openapi-generator-cli generate \
    --global-property apiTests=false \
    --global-property modelTests=false \
    -i /input/${API_FILE} \
    -o /output \
    -g nodejs-express-server

    prettier --write $OUTPUT_DIR
}

buildServer
